[package]
name = "prolance"
version = "0.1.0"
authors = ["Administrator"]
edition = "2019"

[dependencies]
kafka = {version = "0.8.0", default-features = false, features = ["gzip"]}
evtx = "0.4.1"
serde_json = "1.0.40"
zip = "0.5.3"
json = "0.12.0"
job_scheduler = "*"
